//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumTime.Foundation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrumTime.Foundation.Resources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned To may not be more than 120 characters long..
        /// </summary>
        internal static string AssignedToMaxLength120 {
            get {
                return ResourceManager.GetString("AssignedToMaxLength120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned To is required..
        /// </summary>
        internal static string AssignedToRequired {
            get {
                return ResourceManager.GetString("AssignedToRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description may not be more than 1000 characters long..
        /// </summary>
        internal static string DescriptionLength1000 {
            get {
                return ResourceManager.GetString("DescriptionLength1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description may not be more than 120 characteres long..
        /// </summary>
        internal static string DescriptionLength120 {
            get {
                return ResourceManager.GetString("DescriptionLength120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        internal static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name is required..
        /// </summary>
        internal static string FileNameRequired {
            get {
                return ResourceManager.GetString("FileNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Date.
        /// </summary>
        internal static string FinishDateLabel {
            get {
                return ResourceManager.GetString("FinishDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours Completed must be between 0.0 and 40.0 hours..
        /// </summary>
        internal static string HoursCompletedRange0_40 {
            get {
                return ResourceManager.GetString("HoursCompletedRange0_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours must be between 0.0 and 40.0 hours..
        /// </summary>
        internal static string HoursRange0_40 {
            get {
                return ResourceManager.GetString("HoursRange0_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours Remaining must be between 0.0 and 40.0 hours..
        /// </summary>
        internal static string HoursRemainingRange0_40 {
            get {
                return ResourceManager.GetString("HoursRemainingRange0_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name may not be more than 120 characters long..
        /// </summary>
        internal static string NameLength120 {
            get {
                return ResourceManager.GetString("NameLength120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrative may not be more 1000 characters long..
        /// </summary>
        internal static string NarrativeLength1000 {
            get {
                return ResourceManager.GetString("NarrativeLength1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrative is required..
        /// </summary>
        internal static string NarrativeRequired {
            get {
                return ResourceManager.GetString("NarrativeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points must be between 0 and 100..
        /// </summary>
        internal static string Points0_100 {
            get {
                return ResourceManager.GetString("Points0_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string StartDateLabel {
            get {
                return ResourceManager.GetString("StartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        internal static string TextDirection {
            get {
                return ResourceManager.GetString("TextDirection", resourceCulture);
            }
        }
    }
}
