// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace ScrumTime.Controllers {
    public partial class ScheduleController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ScheduleController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult UpdateCalendar() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.UpdateCalendar);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ScheduleController Actions { get { return MVC.Schedule; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Schedule";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string ReleaseList = "ReleaseList";
            public readonly string SprintList = "SprintList";
            public readonly string UpdateCalendar = "UpdateCalendar";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Index = "~/Views/Schedule/Index.ascx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ScheduleController: ScrumTime.Controllers.ScheduleController {
        public T4MVC_ScheduleController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ReleaseList() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ReleaseList);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SprintList() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SprintList);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult UpdateCalendar(string startDateRange, string endDateRange) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.UpdateCalendar);
            callInfo.RouteValueDictionary.Add("startDateRange", startDateRange);
            callInfo.RouteValueDictionary.Add("endDateRange", endDateRange);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
