// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC {
    public class SharedController {

        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string FooterControl = "~/Views/Shared/FooterControl.cshtml";
            public readonly string HeaderControl = "~/Views/Shared/HeaderControl.cshtml";
            public readonly string Layout = "~/Views/Shared/Layout.cshtml";
            public readonly string LogOnUserControl = "~/Views/Shared/LogOnUserControl.cshtml";
            public readonly string MainMenu = "~/Views/Shared/MainMenu.cshtml";
            public readonly string NonAuthenticatingLayout = "~/Views/Shared/NonAuthenticatingLayout.cshtml";
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
