// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace ScrumTime.Controllers {
    public partial class SprintController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SprintController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ListByStartDateDesc() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ListByStartDateDesc);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ReadOnly() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ReadOnly);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Edit() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult New() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.New);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Save() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Save);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Delete() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Delete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Graph() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Graph);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SetCurrent() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SetCurrent);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SprintController Actions { get { return MVC.Sprint; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Sprint";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string ListContainerByStartDateDesc = "ListContainerByStartDateDesc";
            public readonly string ListByStartDateDesc = "ListByStartDateDesc";
            public readonly string ReadOnly = "ReadOnly";
            public readonly string Edit = "Edit";
            public readonly string New = "New";
            public readonly string CurrentSprintName = "CurrentSprintName";
            public readonly string Save = "Save";
            public readonly string Delete = "Delete";
            public readonly string Graph = "Graph";
            public readonly string CurrentEdit = "CurrentEdit";
            public readonly string CurrentReadOnly = "CurrentReadOnly";
            public readonly string SetCurrent = "SetCurrent";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string CurrentEdit = "~/Views/Sprint/CurrentEdit.cshtml";
            public readonly string CurrentReadOnly = "~/Views/Sprint/CurrentReadOnly.cshtml";
            public readonly string Edit = "~/Views/Sprint/Edit.cshtml";
            public readonly string List = "~/Views/Sprint/List.cshtml";
            public readonly string ListContainer = "~/Views/Sprint/ListContainer.cshtml";
            public readonly string ReadOnly = "~/Views/Sprint/ReadOnly.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_SprintController: ScrumTime.Controllers.SprintController {
        public T4MVC_SprintController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ListContainerByStartDateDesc() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ListContainerByStartDateDesc);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ListByStartDateDesc(int productId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ListByStartDateDesc);
            callInfo.RouteValueDictionary.Add("productId", productId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ReadOnly(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ReadOnly);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult New(int productId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.New);
            callInfo.RouteValueDictionary.Add("productId", productId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CurrentSprintName() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CurrentSprintName);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Save(System.Web.Mvc.FormCollection collection) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Save);
            callInfo.RouteValueDictionary.Add("collection", collection);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Delete(int id, System.Web.Mvc.FormCollection collection) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Delete);
            callInfo.RouteValueDictionary.Add("id", id);
            callInfo.RouteValueDictionary.Add("collection", collection);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Graph(string startDateRange, string endDateRange) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Graph);
            callInfo.RouteValueDictionary.Add("startDateRange", startDateRange);
            callInfo.RouteValueDictionary.Add("endDateRange", endDateRange);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CurrentEdit() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CurrentEdit);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CurrentReadOnly() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CurrentReadOnly);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SetCurrent(int sprintId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SetCurrent);
            callInfo.RouteValueDictionary.Add("sprintId", sprintId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
