// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace ScrumTime.Controllers {
    public partial class TaskController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected TaskController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult StoryTaskBacklog() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.StoryTaskBacklog);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ListById() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ListById);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Edit() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ReadOnly() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ReadOnly);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult New() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.New);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult TotalTaskHours() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.TotalTaskHours);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Save() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Save);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Delete() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Delete);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public TaskController Actions { get { return MVC.Task; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Task";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string StoryTaskBacklog = "StoryTaskBacklog";
            public readonly string ListById = "ListById";
            public readonly string Edit = "Edit";
            public readonly string ReadOnly = "ReadOnly";
            public readonly string New = "New";
            public readonly string TotalTaskHours = "TotalTaskHours";
            public readonly string Save = "Save";
            public readonly string Delete = "Delete";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Edit = "~/Views/Task/Edit.cshtml";
            public readonly string List = "~/Views/Task/List.cshtml";
            public readonly string ReadOnly = "~/Views/Task/ReadOnly.cshtml";
            public readonly string StoryTaskBacklog = "~/Views/Task/StoryTaskBacklog.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_TaskController: ScrumTime.Controllers.TaskController {
        public T4MVC_TaskController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult StoryTaskBacklog(int storyId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.StoryTaskBacklog);
            callInfo.RouteValueDictionary.Add("storyId", storyId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ListById(int storyId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ListById);
            callInfo.RouteValueDictionary.Add("storyId", storyId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ReadOnly(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ReadOnly);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult New(int storyId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.New);
            callInfo.RouteValueDictionary.Add("storyId", storyId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult TotalTaskHours(int storyId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.TotalTaskHours);
            callInfo.RouteValueDictionary.Add("storyId", storyId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Save(System.Web.Mvc.FormCollection collection) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Save);
            callInfo.RouteValueDictionary.Add("collection", collection);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Delete(int id, System.Web.Mvc.FormCollection collection) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Delete);
            callInfo.RouteValueDictionary.Add("id", id);
            callInfo.RouteValueDictionary.Add("collection", collection);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
